# 服务端口配置
server:
  port: 4558

# mybatis配置
mybatis:
  check-config-location: true
  config-location: "classpath:mybatis/mybatis-config.xml"
  mapper-locations: "classpath:mybatis/mapper/*Mapper.xml"
  type-aliases-package: "com.wzllby.entity.*"

# 数据库连接配置
spring:
  datasource:
    url: jdbc:mysql://47.119.131.127:3306/blog?useUnicode=true&characterEncoding=UTF8&autoReconnect=true&zeroDateTimeBehavior=convertToNull&useSSL=true&serverTimezone=UTC
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: lby521...
  data:
    redis:
      database: 0
      host: 47.119.131.127
      port: 6379

